# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qUAZFWqccV_5KBjBiKACtXNo86Sm51V_
"""

from setuptools import setup, find_packages

setup(
    name="github_api_package",
    version="0.1",
    packages=find_packages(),
    install_requires=[
        'requests',
    ],
)