# -*- coding: utf-8 -*-
"""github_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qUAZFWqccV_5KBjBiKACtXNo86Sm51V_
"""

import requests
import json
from pprint import pprint

def get_github_user_data(token):
    url = 'https://api.github.com/user'
    headers = {'Authorization': 'Bearer ' + token}
    response = requests.get(url, headers=headers)
    response.raise_for_status()  # Raise HTTPError for bad responses
    return json.loads(response.text)